### ISSUE TITLE
Error 500 when displaying an issue

### ISSUE THREAD

**Issue by frconil** [TravisSpangle/redmine_spent_time_in_issue_description#13] opened 2014-11-27 01:34 UTC
Referring to https://github.com/TravisSpangle/redmine_spent_time_in_issue_description/issues/12 :

Hi,

I can access the config panel for the plugin after installing v2 of the plugin and running the necessary rake tasks (as per http://www.redmine.org/projects/redmine/wiki/Plugins) to remove the old version and install the new one, but now I get the following error when trying to display an issue:

```
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"17413"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (5.6ms)
  Rendered plugins/redmine_contacts/app/views/deals_issues/_show.html.erb (2.5ms)
  Rendered plugins/redmine_contacts_helpdesk/app/views/issues/_ticket_data.html.erb (0.1ms)
  Rendered attachments/_links.html.erb (10.4ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (5.7ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (4.3ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (15.5ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (5.2ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (4.4ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (4.4ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (4.5ms)
  Rendered plugins/redmine_issue_checklist/app/views/issue_checklists/_checklist_item.html.erb (4.5ms)
  Rendered plugins/redmine_issue_checklist/app/views/issues/_checklist.html.erb (55.5ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/_time_spent_report.html.erb (4.8ms)
  Rendered plugins/redmine_spent_time_in_issue_description/app/views/issues/show.html.erb within layouts/base (133.2ms)
Completed 500 Internal Server Error in 348.5ms

ActionView::Template::Error (undefined method `is_spent_on_shown' on an instance of #<Class:0x78c9c>.):
    15:   <tbody>
    16:     <% @issue.time_entries.last( Setting.plugin_redmine_spent_time_in_issue_description['spent_time_max_display'].to_i ).each do |entry| %>
    17:       <tr>
    18:         <%= content_tag(:td, entry.spent_on.strftime("%m/%d/%Y") ) if is_spent_on_shown( entry ) %>
    19:         <%= content_tag(:td, link_to_user( entry.user )) if is_user_shown( entry ) %>
    20:         <%= content_tag(:td, report_time_spent( entry ) ) if is_report_time_shown( entry ) %>
    21:         <%= content_tag(:td, entry.comments ) if is_comment_shown( entry ) %>
  app/controllers/issues_controller.rb:128:in `show'
  app/controllers/issues_controller.rb:125:in `show'
```

**Comment by shuozhifenxi** [comment] 2015-01-03 00:10
I have the same issue.

It seems that the redmine_checklist plugin somehow has some problem with this plugin. (Maybe the both tried to chage the issue view?)

I really love the ideas of the both plugins, and I hope they can work togother.

**Comment by TravisSpangle** [comment] 2015-01-27 22:19
Good news is that I'm able to reproduce the error with https://github.com/Undev/redmine_issue_checklist and Redmine 2.6 with the redmine_spent_time_in_issue_description plugin.

**Comment by shuozhifenxi** [comment] 2015-02-06 16:47
So could you tell us what is the cause of this error please?

**Comment by TravisSpangle** [comment] 2015-02-06 17:20
The error stops when I remove lines 21-23 of redmine_issue_checklist/patches/issues_controller_patch.rb. Specifically it's the IssuesController variable that triggers it. 

The current guess is that I implemented the issue helper module as a patch when I should have just included into the controller.

**Comment by TravisSpangle** [comment] 2015-02-13 00:23
I think I've got it fixed now. Would someone mind confirming so I can close this issue?

**Comment by Pierstoval** [comment] 2015-02-13 08:12
I'm gonna test this next week-end, I don't have ssh access to my server from work ;)

**Comment by Pierstoval** [comment] 2015-02-14 11:29
No problem for me, works fine :+1:

**Closed** 2015-02-14 16:36 UTC

**Comment by jansor** [comment] 2015-04-07 15:53
I have the same issue under redmine 2.5.3. Is this the same problem? how can i resolve it?
