### ISSUE TITLE
rake failed - LoadError: cannot load such file -- Digest

### ISSUE THREAD

**Issue by HeuJung** [TravisSpangle/redmine_spent_time_in_issue_description#28] opened 2015-07-28 01:07 UTC
redmine@redmine:~/redmine$ rake redmine:plugins:migrate RAILS_ENV=production
/usr/local/rvm/gems/ruby-2.2.0/gems/liquid-2.4.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
rake aborted!
LoadError: cannot load such file -- Digest
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/redmine/plugins/redmine_spent_time_in_issue_description/lib/setup_issue_show.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/redmine/plugins/redmine_spent_time_in_issue_description/init.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/redmine/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine/redmine/lib/redmine/plugin.rb:146:in `each'
/opt/redmine/redmine/lib/redmine/plugin.rb:146:in `load'
/opt/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/opt/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Polyglot::PolyglotLoadError: Failed to load /opt/redmine/redmine/config/environment.rb using extensions rb
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:55:in `load'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:68:in `rescue in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
redmine@redmine:~/redmine$ 

Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            1.9.1
  Filesystem                     
  Xitolite                       1.9.1
Redmine plugins:
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  file_servers                   3.0.0
  localizable                    0.4.0
  progressive_projects_list      2.0.1
  quick_edit                     0.0.8
  quick_view                     0.1.0
  redcase                        1.0
  redmine_add_to_calendar        0.0.2
  redmine_agile                  1.3.9
  redmine_banner                 0.1.1
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.1.1
  redmine_ckeditor               1.1.0
  redmine_code_review            0.7.0
  redmine_codemirror             0.0.1
  redmine_contacts               4.0.1
  redmine_contacts_invoices      4.0.0
  redmine_custom_workflows       0.1.4
  redmine_dashboard              2.5.0
  redmine_default_custom_query   1.1.2
  redmine_dmsf                   1.5.2
  redmine_document_move          0.1.0
  redmine_documents              1.0.0
  redmine_git_hosting            1.1.1
  redmine_improved_searchbox     0.0.3
  redmine_issue_completion       0.0.2
  redmine_issue_favicon          0.0.1
  redmine_issue_templates        0.1.0
  redmine_jenkins                1.0.1
  redmine_ldap_sync              2.0.6.g0aec5b8345
  redmine_lightbox2              0.2.2
  redmine_local_avatars          1.0.0
  redmine_logs                   0.1.0
  redmine_monitoring_controlling 0.1.1
  redmine_my_page                0.1.5
  redmine_products               2.0.0
  redmine_remote_revision_url    0.3.0
  redmine_revision_branches      0.2.0
  redmine_spent_time             3.0.2
  redmine_stats                  0.0.3
  redmine_wiki_extensions        0.7.0
  redmine_wiki_lists             0.0.6
  redmine_work_time              0.3.1
  redmine_xlsx_format_issue_exporter 0.1.2
  rmp_group_watchers             1.0.0
  sidebar_hide                   0.0.7
  timelog_timer                  2.0.0
  view_customize                 1.1.2

**Comment by TravisSpangle** [comment] 2015-07-28 01:56
Dag, I thought Digest was more available. I submitted a fix but cannot test until tomorrow. If you want you can check out branch 'digest_fix' and try that. Let me know how it responds. 

Thanks for reporting!

**Comment by janekska** [comment] 2015-07-28 08:14
I had the same problem with my setup:

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_dashboard              2.5.0
  redmine_mail_reminder          3.0.0.0001
  redmine_theme_changer          0.2.0
  redmine_work_time              0.3.1
  time_logger                    0.5.2

I tried the fix. Migration went fine, but the redmine opened with error on any page.

**Comment by ppoektos** [comment] 2015-07-28 13:12
Same here with 2.6.x
```
rake aborted!
LoadError: cannot load such file -- Digest
```

**Comment by TravisSpangle** [comment] 2015-07-28 14:16
Thank you janekska! What error did you get?

**Comment by janekska** [comment] 2015-07-28 14:40
Ups, sorry - where to find them?
I already removed and erased the fix... :-(

In /path/to/redmine/log I do not see something strange... nether in apache
logs.

2015-07-28 17:16 GMT+03:00 Travis <notifications@github.com>:

**Comment by TravisSpangle** [comment] 2015-07-28 15:43
That's Okay, I merged the fix into master. Checkout Master, pull, and you should get the error.

**Comment by janekska** [comment] 2015-07-29 07:01
It is working.

It was caused by wring permissions.

brgds and thank you for your work!

2015-07-28 18:43 GMT+03:00 Travis <notifications@github.com>:

**Closed** 2015-07-29 15:54 UTC
